title: Sneaker Capitale
description: Australian sneaker news, release dates, and drops.
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Update this once you buy your domain, e.g. sneakercapitale.com.au
url: ""
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
